final Map<String, String> diseaseToDepartment = {
  'Fungal infection': 'Dermatology',
  'Allergy': 'Immunology',
  'GERD': 'Gastroenterology',
  'Chronic cholestasis': 'Gastroenterology',
  'Drug Reaction': 'Internal Medicine',
  'Peptic ulcer disease': 'Gastroenterology',
  'AIDS': 'Infectious Disease',
  'Diabetes': 'Endocrinology',
  'Gastroenteritis': 'Gastroenterology',
  'Bronchial Asthma': 'Pulmonology',
  'Hypertension': 'Cardiology',
  'Migraine': 'Neurology',
  'Cervical spondylosis': 'Orthopedics',
  'Paralysis (brain hemorrhage)': 'Neurology',
  'Jaundice': 'Hepatology',
  'Malaria': 'Infectious Disease',
  'Chicken pox': 'Infectious Disease',
  'Dengue': 'Infectious Disease',
  'Typhoid': 'Infectious Disease',
  'Hepatitis A': 'Hepatology',
  'Hepatitis B': 'Hepatology',
  'Hepatitis C': 'Hepatology',
  'Hepatitis D': 'Hepatology',
  'Hepatitis E': 'Hepatology',
  'Alcoholic hepatitis': 'Hepatology',
  'Tuberculosis': 'Pulmonology',
  'Common Cold': 'General Medicine',
  'Pneumonia': 'Pulmonology',
  'Dimorphic hemorrhoids (piles)': 'General Surgery',
  'Heart attack': 'Cardiology',
  'Varicose veins': 'Vascular Surgery',
  'Hypothyroidism': 'Endocrinology',
  'Hyperthyroidism': 'Endocrinology',
  'Hypoglycemia': 'Endocrinology',
  'Osteoarthritis': 'Orthopedics',
  'Arthritis': 'Rheumatology',
  '(vertigo) Paroxysmal Positional Vertigo': 'Neurology',
  'Acne': 'Dermatology',
  'Urinary tract infection': 'Urology',
  'Psoriasis': 'Dermatology',
  'Impetigo': 'Dermatology',
};
