Map<String, String> categoryIcons = {
  "General": "assets/images/icons/general.png",
  "Skin & Rashes": "assets/images/icons/Skin.png",
  "Breathing & Chest": "assets/images/icons/lungs.jpg",
  "Stomach & Digestion": "assets/images/icons/stomach.jpg",
  "Head & Nerves": "assets/images/icons/head.jpg",
  "Joints, Bones & Muscles": "assets/images/icons/bones.jpg",
  "Urine/Reproductive": "assets/images/icons/reproductive.jpg",
  "Hormones & Weight": "assets/images/icons/hormones.png",
  "Liver": "assets/images/icons/liver.jpg",
  "Swelling & Immunity": "assets/images/icons/swelling.jpg",
  "Mood, Stress & Mind": "assets/images/icons/mind.png",
  "Sexual Health": "assets/images/icons/sexualHealth.png",
  "Heart & Circulation": "assets/images/icons/heart.jpg",
  "Eyes, Nose & Throat": "assets/images/icons/ent.jpg",
  "Anal & Rectal": "assets/images/icons/rectal.jpg",
};

const Map<String, List<String>> symptomCategories = {
  "General": [
    "high fever",
    "mild fever",
    "chills",
    "shivering",
    "sunken eyes",
    "sweating",
    "dehydration",
    "fatigue",
    "weight loss",
    "weight gain",
    "lethargy",
    "malaise",
    "weakness",
    "fluid overload",
    "toxic look (typhos)",
    "prognosis",
  ],
  "Skin & Rashes": [
    "itching",
    "skin rash",
    "nodal skin eruptions",
    "ulcers on tongue",
    "pus filled pimples",
    "blackheads",
    "scurring",
    "skin peeling",
    "silver like dusting",
    "small dents in nails",
    "inflammatory nails",
    "blister",
    "red sore around nose",
    "yellow crust ooze",
    "dischromic patches",
    "red spots over body",
  ],
  "Breathing & Chest": [
    "continuous sneezing",
    "cough",
    "phlegm",
    "throat irritation",
    "sinus pressure",
    "runny nose",
    "congestion",
    "chest pain",
    "breathlessness",
    "mucoid sputum",
    "rusty sputum",
    "blood in sputum",
    "cold hands and feets",
  ],
  "Stomach & Digestion": [
    "stomach pain",
    "acidity",
    "vomiting",
    "nausea",
    "diarrhoea",
    "constipation",
    "indigestion",
    "abdominal pain",
    "belly pain",
    "loss of appetite",
    "passage of gases",
    "distention of abdomen",
    "stomach bleeding",
  ],
  "Head & Nerves": [
    "dizziness",
    "slurred speech",
    "altered sensorium",
    "spinning movements",
    "loss of balance",
    "unsteadiness",
    "weakness of one body side",
    "headache",
    "lack of concentration",
    "visual disturbances",
    "coma",
  ],
  "Joints, Bones & Muscles": [
    "joint pain",
    "back pain",
    "muscle wasting",
    "knee pain",
    "hip joint pain",
    "muscle weakness",
    "swelling joints",
    "movement stiffness",
    "stiffness in neck",
    "cramps",
    "weakness in limbs",
    "neck pain",
    "pain during bowel movements",
    "painful walking",
  ],
  "Urine/Reproductive": [
    "burning micturition",
    "spotting urination",
    "bladder discomfort",
    "foul smell of urine",
    "continuous feel of urine",
    "polyuria",
    "abnormal menstruation",
  ],
  "Hormones & Weight": [
    "irregular sugar level",
    "increased appetite",
    "excessive hunger",
    "obesity",
    "enlarged thyroid",
    "puffy face and eyes",
    "brittle nails",
  ],
  "Liver": [
    "yellowish skin",
    "dark urine",
    "yellow urine",
    "yellowing of eyes",
    "acute liver failure",
    "swelling of stomach",
    "history of alcohol consumption",
  ],
  "Swelling & Immunity": [
    "swelled lymph nodes",
    "patches in throat",
    "red sore around nose",
    "inflammation-related symptoms",
    "prognosis",
  ],
  "Mood, Stress & Mind": [
    "anxiety",
    "mood swings",
    "depression",
    "irritability",
    "lack of concentration",
  ],
  "Sexual Health": [
    "extra marital contacts",
    "receiving blood transfusion",
    "receiving unsterile injections",
    "family history",
  ],
  "Heart & Circulation": [
    "palpitations",
    "fast heart rate",
    "swollen legs",
    "swollen blood vessels",
    "prominent veins on calf",
  ],
  "Eyes, Nose & Throat": [
    "pain behind the eyes",
    "watering from eyes",
    "redness of eyes",
    "blurred and distorted vision",
    "loss of smell",
  ],
  "Anal & Rectal": [
    "pain in anal region",
    "bloody stool",
    "irritation in anus",
  ],
};
